### ISSUE TITLE
move tool bug

### ISSUE THREAD

**Issue by Loshhhs** [SwiftyETH/Elite-Engineering#11]
**Describe the bug**
Makes your move tool not work, I tried to duplicate something while moving it and it broke the move tool, 

**To Reproduce**
1. get some parts
2. try and duplicate the parts while moving it
3. *note* i cannot seem to replicate it again but that is what I did and i cannot seem to refine on what it went down to

**Expected behavior**
breaks you move tool, has those lines when ever you are movign still there

**Screenshots**
![image](https://user-images.githubusercontent.com/81268779/150703541-cccc4de3-c50f-4de2-9b89-5a83e0e7bd0c.png)

**Desktop (please complete the following information):**
windows 10

**Additional context**

**Comment by SwiftyETH** [comment]
Resolved!
