### ISSUE TITLE
Parts Glowing From Tools

### ISSUE THREAD

**Issue by DylanG1105** [SwiftyETH/Elite-Engineering#12]
**Describe the bug**
Parts continue to hover selection glowing

**To Reproduce**
1. Select any tool
2. Hover over a part
3. Unselect tool

**Expected behavior**
part wouldn't continue to glow

**Screenshots**
https://gyazo.com/721cb2c36bb28aa8e0d77c184a80fe63

**Desktop (please complete the following information):**
windows

**Additional context**

**Comment by SwiftyETH** [comment]
Fix created for next update
