### ISSUE TITLE
Tools Breaking bug

### ISSUE THREAD

**Issue by koloozer** [SwiftyETH/Elite-Engineering#14]
**Describe the bug**
Tools refuse to function, bug fixed whenever player rejoins

**To Reproduce**
extensive use of tools, swapping between move and resize quickly may reproduce it

**Expected behavior**
may cause mirroring bugs and part shifting (a given)

**Screenshots**
https://imgur.com/a/daDAFpN

**Desktop (please complete the following information):**
 - OS: Windows 11

**Additional context**
N/A

**Comment by koloozer** [comment]
**Describe the bug**
Phantom Move tool bug, doesnt seem to affect parts

**To Reproduce**
Steps to reproduce the behavior:
extensive use of tools, swapping between move and resize quickly may reproduce it

**Expected behavior**
may cause mirroring bugs

**Screenshots**
https://imgur.com/a/wmJZdIk

**Comment by SwiftyETH** [comment]
Thanks ill have a look into it, from the looks of it, it seems that it thinks there are no parts selected??

**Comment by SwiftyETH** [comment]
This issue looks very similar to issue #15
