### ISSUE TITLE
phantom selecton of other parts

### ISSUE THREAD

**Issue by mechasharkfin** [SwiftyETH/Elite-Engineering#15]
**Describe the bug**
attempting to move only the wedge as seen in the gif also moves the two blocks perpendicular to it. 

**To Reproduce**
not sure if this will actually reproduce but heres what i did:
open mirror mode in z axis
place a block on the ground and size them up, making the two sides touch.
move them up with local mode (maybe this screwed them up) 
add a wedge
now i can no longer deselect the block while attempting to move / resize the wedge

**Expected behavior**
able to move the wedge without moving block

**Screenshots**
https://gyazo.com/556e5da2e657df8fc57167a58f50a34b

**Desktop (please complete the following information):**
 - OS: mac

**Additional context**
managed to fix it actually by waiting a while before opening up a tool again. so not sure if i was just being dumb

**Comment by mechasharkfin** [comment]
https://gyazo.com/4eb72bc1117cc8d9f82e0fb4969604c0 happened again but this time on a larger scale. parts on both sides would shift in random directions and after fixing one side the other would resize very weirdly.

**Comment by SwiftyETH** [comment]
I'll have a look into this issue, did it have any console errors for either of them?
