### ISSUE TITLE
rotation reset

### ISSUE THREAD

**Issue by mechasharkfin** [SwiftyETH/Elite-Engineering#17]
**Is your feature request related to a problem? Please describe.**
often if you want to fully reset the rotation of the block you have to 1. type it in or 2. just spawn a new block. adding this feature would be pretty poggers (im preeetty sure it was in old ee but not entirely)

**Describe the solution you'd like**
omg! this part is rotated really weirdly at -23 57 102 ill just press this button and now its at 0 0 0 again!

**Describe alternatives you've considered**
typing 0 0 0 in or placing new part

**Comment by SwiftyETH** [comment]
You can drag a block to reset its rotation.

As for your description of the fix, should it reset all currently selected parts back to 0,0,0

**Comment by SwiftyETH** [comment]
Will be applied in next update.
