### ISSUE TITLE
differnte type of steats

### ISSUE THREAD

**Issue by Loshhhs** [SwiftyETH/Elite-Engineering#18]
**dif types of seats more then just passenger and driver seat**

**seat called pilot seat**
the pilot seat has more values and changeable stuff in logic, like how seat only had 2 variables, throttle and turn, maybe you could be able to change how much it outputs or have more types of outputs maybe for weapons or for lights idk how you would make this block better but this is my idea, 

maybe the driver seat could be limited how many things can be hooked up to it like, you hook the throttle up to 20 motors but it can only handle 25 motors but the pilot seat increases that cap to 50 or smt

**cons**
would take up more space and would have a decently sized screen infront of you

**Comment by SwiftyETH** [comment]
I dont see this really adding anything to the game...

**Comment by Loshhhs** [comment]
higher limits n stuff

**Comment by SwiftyETH** [comment]
limits to what? a driver seat can control 1000's of parts at once

**Comment by Loshhhs** [comment]
yeah thats what i ment, you lower the driver seats control to like 250 and make pilot to 1k, it doesnt make sense to have a really small block that can control so many things, would add some real factor that you would need a bigger and badder seat to control more
