### ISSUE TITLE
resize does not work at large distances

### ISSUE THREAD

**Issue by mechasharkfin** [SwiftyETH/Elite-Engineering#19]
**Describe the bug**
resize does not work at larger distances. only lets you resize when close to the part

**To Reproduce**
1. add part
2. scroll out
3. resize in any direction

**Expected behavior**
this does not happen with move tool or rotation tool so its quite weird to not be able to do this

**Screenshots**
https://gyazo.com/da5693ef348fd5fe1ca74fdec98fc8df

**Desktop (please complete the following information):**
 - mac

**Comment by SwiftyETH** [comment]
this just happens because you are resizing it wayyy past its allowed amount so it stops it, a fix for this is to round it to the lowest allowed amount for that increment. not really a "bug" but yeah its something i can fix and will fix.

**Comment by SwiftyETH** [comment]
Fix for this on next update.
