### ISSUE TITLE
Duplicate, Not so smooth moving, rotating, resizing 

### ISSUE THREAD

**Issue by WULF9339** [SwiftyETH/Elite-Engineering#2]
Thats just it, I have a low end pc yes but not a complete potato one and I find resizing, moving, rotating kinda un-smooth
I mean if you're making a game, you try your best to make it compatible with alot of devices yes yes

**Comment by WULF9339** [comment]
Also, when duplicating the duplicated part just stays where the original part was I don't know if I'm doing it wrong but yea

**Comment by SwiftyETH** [comment]
> Also, when duplicating the duplicated part just stays where the original part was I don't know if I'm doing it wrong but yea

That is perfectly normal, duplicating keeps the part in the same place for good reason :)



> Thats just it, I have a low end pc yes but not a complete potato one and I find resizing, moving, rotating kinda un-smooth I mean if you're making a game, you try your best to make it compatible with alot of devices yes yes

I have a fix coming soon to address this, should make things smoother.

**Comment by SwiftyETH** [comment]
Made dragging smoother and more performant by reducing the rate of update.
