### ISSUE TITLE
keybind menu breaking

### ISSUE THREAD

**Issue by Loshhhs** [SwiftyETH/Elite-Engineering#20]
**Describe the bug**
basicially you get stuck on CONFIRM leave keybind menu

**To Reproduce**
1. go to change a keybind, while its saving press cancel
2. wait a second or two
3. press confirm and it should pop up errors

**Screenshots**
![image](https://user-images.githubusercontent.com/81268779/151039015-58c53898-6d6c-44d9-bc75-f715b2299516.png)

**Comment by Loshhhs** [comment]
it also breaks all your keybinds forcijg you to rejoin

**Comment by SwiftyETH** [comment]
Fix created for next update
