### ISSUE TITLE
Position, rotation and scale do not properly apply after creating a new part

### ISSUE THREAD

**Issue by Thelord400005** [SwiftyETH/Elite-Engineering#21]
Describe the bug: 
The bug appears to be a misfire of the script that controls and updates the rotation, scale and position of the block, although it could be a client - side malfunction of the Roblox engine, in either case, the bug happens as a new part is created, scaled, manipulated, etc. After saving, duplicating or copy and pasting, one can tell the part has not moved at all from its original position after being inserted. 

1. Create a new part using tool 5.
2. Move the part to a desired position and rotation.
3. Duplicate the part using the duplicate shortcut.
4. The part reappears on the place it was inserted in. Rotation, scale and position are completely reset. 

Expected behavior:
The duplicate shortcut should create an exact replica of the part it it's designed to duplicate, not an instance of the part it was when it was inserted.

Gif: 

https://user-images.githubusercontent.com/98419805/151038437-718c70f2-b737-4fa9-8352-7e35f48318ed.mp4

(In the video, before pressing the duplicate shortcut, I attempted to reinsert the block by deleting it and re-doing it, to see if it would properly duplicate, however, the transforms still did not apply, and the block was duplicated as an instance of itself after being created, without any rotations, scale or position applied.)

 - OS: [Windows 10]

Additional context:
I have experienced this bug on past building game experiences, such as BYM and BnD.

**Comment by SwiftyETH** [comment]
This is interesting, thanks for the report.

**Comment by SwiftyETH** [comment]
Hmm... yeah im unable to replicate this issue, it seems to be related to your network conditions?
