### ISSUE TITLE
rotation isnt accurate

### ISSUE THREAD

**Issue by Loshhhs** [SwiftyETH/Elite-Engineering#23]
**Describe the bug**
Basicially in studio your part aligns right nicely, but when you go to export into game. the rotation of the part says what it is in studio. but the values arent actually the same as the part.

**To Reproduce**
1. Go to the rbx file i sent in the discord
2. grab those 4 parts orientation
3. try and corner snap together
4. doesnt align cause orientation is off by a few degrees then what i inserted

**Expected behavior**
the orientation of the part is not the same as the part in studio which i have grabbed the orientation from, using:
![image](https://user-images.githubusercontent.com/81268779/151044558-aebd85b1-d524-4238-8760-d3c4b71b3cab.png)
and zelds specific plugin that converts negative orientations to positive and it produces the exact same result
![image](https://user-images.githubusercontent.com/81268779/151044652-76b1c0ca-abe4-4a33-83bc-b5097897c7ac.png)

**Screenshots**
what it is suposed to look like with proper orientation:
![image](https://user-images.githubusercontent.com/81268779/151044809-de19c3c6-8d04-4ba4-9c5f-53137d0083e6.png)
-----------
what it looks like ingame:
![image](https://user-images.githubusercontent.com/81268779/151044850-d72ba753-613c-47b4-935e-cc6626a839b2.png)

**Comment by Loshhhs** [comment]
more proof of it not working:
my charger that worked in the old game:
![image](https://user-images.githubusercontent.com/81268779/151046363-72acf352-0be2-4eba-b4ec-ef5d67d0eec6.png)
-------------------
ingame:
![image](https://user-images.githubusercontent.com/81268779/151047372-eff15e8c-285f-42c4-baee-7f9193d63fd4.png)

**Comment by SwiftyETH** [comment]
Fixed on next update.
