### ISSUE TITLE
Mirror Bug

### ISSUE THREAD

**Issue by koloozer** [SwiftyETH/Elite-Engineering#24]
**Describe the bug**
Although parts are perfectly mirrored, they are not selected with the mirror mode tool, occasionally parts aren't selected with the mirror tool and have to be selected manually to mirror.

**To Reproduce**
use the copy and paste command on existing blocks and mirror them perfectly, happens after 2-3 saves.

**Expected behavior**
(i dont know what it means by what i expected to happen)
i expect that the mirroring may have to do with scanning selection, not sure.

**Screenshots + Video**
Screenshot may not relate to the provided error
https://streamable.com/y2tst3
https://imgur.com/a/MdH4ryT

**Desktop (please complete the following information):**
 - OS: Windows 11

**Additional context**
N/A

**Comment by SwiftyETH** [comment]
Will be fixed in next update.
