### ISSUE TITLE
Copy parts to other saves

### ISSUE THREAD

**Issue by koloozer** [SwiftyETH/Elite-Engineering#25]
**Is your feature request related to a problem? Please describe.**
BND and BYM used the copy glitch to duplicate parts, this glitch does not work in this game.

**Describe the solution you'd like**
The ability to use either the copy glitch or the copy/paste feature within the tools to allow for parts to traverse saves

**Describe alternatives you've considered**
attempting to use the copy glitch as is

**Additional context**
N/a

**Comment by SwiftyETH** [comment]
Yes this is intentional, copying/pasting does not work across saves.
The next update has allowed copy/paste to work across saves.
