### ISSUE TITLE
Increment menu stacking bug

### ISSUE THREAD

**Issue by UltimaPrime** [SwiftyETH/Elite-Engineering#31]
**Describe the bug**
Increment menu primary stacking to secondary (or vise versa) 

**To Reproduce**
Random Rare occasions

**Screenshots**
![image](https://user-images.githubusercontent.com/98471627/151190331-8d091fae-abff-4606-b80c-a5e5d709a16b.png)

**Desktop (please complete the following information):**
 - OS: Desktop

**Comment by SwiftyETH** [comment]
Next update has this fixed.
