### ISSUE TITLE
Mirror Mode Select

### ISSUE THREAD

**Issue by DylanG1105** [SwiftyETH/Elite-Engineering#33]
**Describe the bug**
a part without a mirror mode counterpart can select other parts previously associated with another mirror mode counterpart.

**To Reproduce**
1. Have 2 mirrored parts
2. Exit mirror mode
3. Add another part with the same rotation as the other 2 parts near to one of the other mirror mode parts
4. Try selecting the previous parts and also the newly added part

**Expected behavior**
It wouldn't select the other part

**Screenshots**
https://gyazo.com/bd20f1137b9e70e540a8b7b36863f979

**Desktop (please complete the following information):**
windows

**Additional context**

**Comment by SwiftyETH** [comment]
Just how it works
