### ISSUE TITLE
mirror mode innacuracy

### ISSUE THREAD

**Issue by Loshhhs** [SwiftyETH/Elite-Engineering#34]
**Describe the bug**
while building your mirror mode can be heavily innacurate. especially the way that i build.

**To Reproduce**
1. start making something thats plated heavily
2. duplicate the parts and dont move them
3. resize them and rotate
4. deselect
5. select again and corner snap

**SCREENSHOTS**

![image](https://user-images.githubusercontent.com/81268779/151226209-767cdcd6-2e89-40c9-89a7-1f324f722a66.png)
as you can see the part is inside the other part as i have deselected it. the game doesnt know which is what because im assuming you do mirror mode by the objects origin

**Expected behavior**
every once in a while it will grab the wrong part or resize the wrong part or rotate the wrong part and it just is annoying. it doesnt happen often but those steps is what i was personally doing it, for it to fuck up and size or rotate or move the wrong part

**Additional context**
note this does not happen very often but when it does i notice that other parts around it like to fuck up too

extra note: i cannot seem to replicate the glitch again but i just wanted to report that the innacuracy is there

**Comment by SwiftyETH** [comment]
Only way to fix this is to force both parts to also have similar size, tho idk...
