### ISSUE TITLE
coupler part (logic)

### ISSUE THREAD

**Issue by Loshhhs** [SwiftyETH/Elite-Engineering#35]
**Is your feature request related to a problem? Please describe.**
basicially lets you connect to other peoples builds. aswell if its connected, all keybinds on that other build aswell is yours is useable. so you dont have to get each other to press stuff when you can do it yourself.

**Describe the solution you'd like**
this block requires some turning on and off functions aswell as its own dedicated keybind, it has a ID which makes it so random players cannot connect and your friend has to make sure their coupler has the same id to connect

**what this could do?**
make much larger builds, team work and working together on a extreme level. ex: making a space station and you and your friends team up to make different parts of it to make a massive creation and launch it into space!

**Comment by SwiftyETH** [comment]
Not possible due to networking constraints. (Only 1 player can take ownership of a build at 1 time)
