### ISSUE TITLE
deleting passenger seat

### ISSUE THREAD

**Issue by Loshhhs** [SwiftyETH/Elite-Engineering#4]
i have no keybind on "R" except my rotate keybind,

i can perfectly fine rotate while inserting but when i go to drag it it resets its orientation and when i go to rotate it again it just disappears and gets deleted.

once again i have no keybind on R except rotating

**Comment by Loshhhs** [comment]
its actually with any part not just the seat

**Comment by Loshhhs** [comment]
update- 
i went into mirror mode and tried to rotate a part inserting something in and one of the seats reappeared and i cannot rotate now,
there are no errors

**Comment by SwiftyETH** [comment]
unable to replicate this issue

**Comment by Loshhhs** [comment]
https://www.youtube.com/watch?v=2e6J_x5PFgM&feature=youtu.be&ab_channel=Loshhs

**Comment by SwiftyETH** [comment]
User error
