### ISSUE TITLE
Move tool breaking other tools

### ISSUE THREAD

**Issue by Cloudyimatree** [SwiftyETH/Elite-Engineering#41]
**Describe the bug**
This is probably a rare bug but whenever i was dragging it shifted a part or two and broke the entire dragging system with a list of errors that have shown
**To Reproduce**
1. Go to the drag tool
2. Select parts
3. Drag

**Expected behavior**
What was expected to happen was the parts to move

**Screenshots**
![image](https://user-images.githubusercontent.com/82341868/151287925-b8e299b3-36c0-444a-b001-ed82876714d9.png)
![image](https://user-images.githubusercontent.com/82341868/151287936-4351165a-5ce2-4fff-ac7e-8d3db376a4c1.png)

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**
When i use the tools after the bug happens none of the tools work and this bug appears every time I try to equip a tool
![image](https://user-images.githubusercontent.com/82341868/151288030-97941340-8e45-498a-b16e-1720c98b2438.png)
and this is the only thing that is shown 
![image](https://user-images.githubusercontent.com/82341868/151288067-9ce63b82-f907-404d-99ee-6e58e90339ab.png)

**Comment by SwiftyETH** [comment]
This is the curse in its prime. As i cannot replicate this issue and dont really know where to begin with searching for what caused this ive adjusted the code to give more intel to you when it does break.

**Comment by SwiftyETH** [comment]
Ive attempted to fix this with a bit of a dodgy fix, but if nothing unexpected happens it should be "safe"
