### ISSUE TITLE
Person's garage still exists after leaving

### ISSUE THREAD

**Issue by UltimaPrime** [SwiftyETH/Elite-Engineering#42]
**Describe the bug**
The garage when a person after they leave still show their name and avatar

**To Reproduce**
Rare

**Screenshots**
![image](https://user-images.githubusercontent.com/98471627/151292770-bfa44ae9-0a9d-4ff1-9265-f7cd63a5da3f.png)

**Desktop (please complete the following information):**
 - OS: PC
 
**Additional context**
This is also can be seen by others and a new person joining wont get rid of it

**Comment by SwiftyETH** [comment]
Fixed on next update.
