### ISSUE TITLE
Phantom copy paste and duplicate

### ISSUE THREAD

**Issue by 1visaliaguy2005** [SwiftyETH/Elite-Engineering#43]
**Describe the bug**

Visual bug that occurs when you press the keys for duplication and copy and paste

**To Reproduce**
1. Without any parts selected, press the keys for duplication or copy and paste
2. See error

**Expected behavior**

I found this on accident while trying to copy a part when my mouse slipped, then further investigated it and tried it with other commands like duplication

**Screenshots**
Include screenshots of the console with all errors included.
https://i.gyazo.com/bd258dc293a8f359114d2b6170d0a03d.mp4
https://i.gyazo.com/8ecd1fd94d9bf3b7d2326f38b6fbef60.mp4
![image](https://user-images.githubusercontent.com/98365813/151295150-76413891-a4a6-4f6e-a533-e92ff9fe3ad6.png)
![image](https://user-images.githubusercontent.com/98365813/151295174-842504d0-7c2e-4b29-a899-08be3a76ec1c.png)

Also try to include gifs and images of the issue at hand. (this can be especially useful for visual issues)

**Desktop (please complete the following information):**

**Additional context**

**Comment by SwiftyETH** [comment]
Solved on next update
