### ISSUE TITLE
EE updates on discord not being complete

### ISSUE THREAD

**Issue by koloozer** [SwiftyETH/Elite-Engineering#46]
**Describe the bug**
When EE is updated, the updates must be under 50 characters or a ellipsis is added

**To Reproduce**
Update the game and type an update message through Github onto the discord server bot

**Screenshots**
![image](https://user-images.githubusercontent.com/98277352/151381316-ea32645f-9f80-445d-ae6c-25ab0d1cd7d5.png)

**Desktop (please complete the following information):**
 - OS: Discord, WIndows 11 1080p screen

**Additional context**
N/A

**Comment by SwiftyETH** [comment]
That isnt actually an update message, I plan on having a proper version of that soon. But basically thats just the version control for me doing stuff locally on my PC (I sometimes will have numerous "commits" per update on EE)

The proper message will be able to support a lot more characters.
