### ISSUE TITLE
Sphere Resizing

### ISSUE THREAD

**Issue by DylanG1105** [SwiftyETH/Elite-Engineering#47]
**Describe the bug**
Spheres (not to be confused with sphere mesh) cannot be resized with 4 of the existing handles
**To Reproduce**
1. try to resize a sphere on each handle until it doesn't resize properly

**Expected behavior**
Sphere should have been resized normally

**Screenshots**
https://gyazo.com/0bfb7eb42710bf59be2f4b315d473a8a

**Desktop (please complete the following information):**
windows

**Additional context**

**Comment by SwiftyETH** [comment]
Solved
