### ISSUE TITLE
Tools/Saving Completely Breaks

### ISSUE THREAD

**Issue by DylanG1105** [SwiftyETH/Elite-Engineering#48]
**Describe the bug**
The game basically does not function anymore. Tools and saving do not work period

**To Reproduce**
1. Make a build with more than the allowed compressed parts
2. Try to unanchor it
3. Move a part

**Expected behavior**
Parts to be able to still be edited without killing the game
**Screenshots**
![image](https://user-images.githubusercontent.com/81646044/151464719-93c569ea-2ffe-43f4-89dc-9261cc6eecb1.png)
![image](https://user-images.githubusercontent.com/81646044/151464766-96018c03-3164-4aa2-95d0-2715cd40ffef.png)

**Desktop (please complete the following information):**
windows

**Additional context**

**Comment by SwiftyETH** [comment]
Relating to the curse believe it or not, which relates to the issues with parts moving even though they are not selected. This is a very tricky bug, which is hard to identify, but I will do some research into it soon.

**Comment by SwiftyETH** [comment]
Hopefully fixed 🙏
