### ISSUE TITLE
Increment Menu Stacking

### ISSUE THREAD

**Issue by DylanG1105** [SwiftyETH/Elite-Engineering#49]
**Describe the bug**
Increments stack on top of each other. The Increment UI stays up even after tools are deselected

**To Reproduce**
Steps to reproduce the behavior: (i really don't know yet and will update if i can find the cause)

**Expected behavior**
It wouldn't overlap
**Screenshots**
![image](https://user-images.githubusercontent.com/81646044/151466208-b8b51674-55a7-4a02-83ce-25a0a0c87df8.png)
![image](https://user-images.githubusercontent.com/81646044/151466321-c37843f2-f36b-4b0e-91cd-f837f42aa057.png)

**Desktop (please complete the following information):**
windows

**Additional context**

**Comment by SwiftyETH** [comment]
Duplicate issue, will fix soon
