### ISSUE TITLE
Mirror Mode Hinges

### ISSUE THREAD

**Issue by DylanG1105** [SwiftyETH/Elite-Engineering#51]
**Describe the bug**
Hinges aren't placed properly in mirror mode

**To Reproduce**
1. turn on mirror mode
2. place a hinge
3. a limits to the hinges

**Expected behavior**
the hinges to be limited the same way on both side
**Screenshots**
![image](https://user-images.githubusercontent.com/81646044/151635872-a6f36938-356a-4838-bb7e-57c958868454.png)

**Desktop (please complete the following information):**
windows

**Additional context**
both hinges have a lower angle of 22 however the one on the left is 180 degrees off from the one on the right

**Comment by SwiftyETH** [comment]
Seems its working as intended, as the hinge block is mirror rotated?
