### ISSUE TITLE
Resize/Move tool errors

### ISSUE THREAD

**Issue by Supernova005** [SwiftyETH/Elite-Engineering#56]
**Describe the bug**
Unwanted parts somehow affected by resize/move tool

**To Reproduce**
1. Load an anchored build
2. Delete a large amount of blocks from the build, hundreds preferably. 
Chances of the method are still unspecified

**Expected behavior**
Reaction of unwanted parts being affected by resize/move tool

**Screenshots**
![bruh](https://user-images.githubusercontent.com/98437260/151657024-e33a4db9-11bf-4f6d-804e-5f25f1bd3ff5.gif)

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**
From what I recall, I deleted approximately around 300 or less parts from this build; I speculate the action caused overriding of ingame code which may have cause the glitch.

**Comment by SwiftyETH** [comment]
this is part of the curse, still researching the bug, rn just rejoin and reload. Theres so little information on it :sob:
