### ISSUE TITLE
liven up the map

### ISSUE THREAD

**Issue by Loshhhs** [SwiftyETH/Elite-Engineering#58]
**Describe the solution you'd like**
make some of the things more bright like for example, the pipes in the garage is a really dark red, you could liven it up by doing a brighter color of red, or instead of red which usually means no power you could do a blue like on the monitors

the terrain is also a bit dark you could increase the brightness of it and the game will feel more vibrant and fun like the old game did

**Additional context**
just overall it just feels a bit dull and like a warzone

**Comment by SwiftyETH** [comment]
Its meant to be a bit dull, I dont really need it to be bright. The colour in the garages is again part of the main colour scheme of the game. Bright colours can look ugly, like it did in old EE.
