### ISSUE TITLE
Changing rope length breaks tools

### ISSUE THREAD

**Issue by Cloudyimatree** [SwiftyETH/Elite-Engineering#59]
**Describe the bug**
When changing the length of ropes using the config tool, the rest of the tools break and you can't click off blocks anymore.
**To Reproduce**
1. Use the config tool on the rope
2. Change the rope length
3. (not too sure about this but this may have been what broke it) Toggle the rope visibility off and on 

**Expected behavior**
I expected for the rope to change length but that did not work at all
**Screenshots**
![image](https://user-images.githubusercontent.com/82341868/151670135-3899d09e-327e-444a-af67-5edde9e4989b.png)

**Desktop (please complete the following information):**

**Additional context**
Now that i think about it, i did put a large number in the rope length and that may have caused it to break.

**Comment by SwiftyETH** [comment]
Fixed
