### ISSUE TITLE
Config tool for ropes does not work

### ISSUE THREAD

**Issue by Cloudyimatree** [SwiftyETH/Elite-Engineering#6]
Changing the rope length does nothing to the rope whether its at 0 or 100

![image](https://user-images.githubusercontent.com/82341868/150701420-a090f9da-00dc-4b38-b027-739349deb464.png)
![image](https://user-images.githubusercontent.com/82341868/150701431-96d026ed-80e8-4180-a5b9-6929a19d5a94.png)

**Comment by SwiftyETH** [comment]
Configurations are only set once you activate build

**Comment by Cloudyimatree** [comment]
o
