### ISSUE TITLE
prismatic rename

### ISSUE THREAD

**Issue by Loshhhs** [SwiftyETH/Elite-Engineering#64]
**Is your feature request related to a problem? Please describe.**
kinda, in bnd balljoints are called shoulderjoints and its kind of wierd. ee has a similarity

**Describe the solution you'd like**
rename sliders back to prismatics, cause its just confusing that it has its own name in studio but in ee its called a slider

allthough i do understand why you decided to name prismatics to sliders for simplicity reasons,

**Comment by SwiftyETH** [comment]
Nah, sliders make sense for players, prismatic confuses the hell out of people. Remember EE is NOT studio :)
