### ISSUE TITLE
Power Balance

### ISSUE THREAD

**Issue by koloozer** [SwiftyETH/Elite-Engineering#65]
**Is your feature request related to a problem? Please describe.**
Bigger = Better

**Describe the solution you'd like**
A power efficiency or throughput system for balancing builds

**Describe alternatives you've considered**
N/A

**Additional context**
To combat bigger generators making for extremely overpowered builds, there should be some form of throughput when it comes to weapons.
I.E Bigger builds shouldn't be able to bully smaller builds, and smaller builds shouldn't be able to absolutely demolish bigger builds, allowing for both to have a fair fight against each other.

I plan to elaborate more through the comments

Screenshots from the game below shows this example clearly, the lighter machine isn't able to do good enough damage to the heavier machine, but it still allows for a fair fight.
![image](https://user-images.githubusercontent.com/98277352/151834461-32f51502-c088-4639-b1a3-19d63677e7b2.png)
![image](https://user-images.githubusercontent.com/98277352/151834423-90507455-7937-40e4-afe1-5ca52e5fbdf0.png)

**Comment by SwiftyETH** [comment]
Bigger is NOT better. Please do not suggest balance changes until you fully understand how these systems will work.
