### ISSUE TITLE
Saving Build Won't Go Through

### ISSUE THREAD

**Issue by MlgEnderDragon456** [SwiftyETH/Elite-Engineering#69]
As of recent, I've added an engine section to the back of my ship. Once I was completed and clicked save, I was confronted with this message: (Image below). I'm not sure why this happened, the engine module is fairly simple and not too complex of a build.
![ThisIsntGood](https://user-images.githubusercontent.com/98863380/152088556-96728890-31ff-492d-aa0f-633d0465e4d3.png)

EDIT: I reloaded, and parts of my build are missing. They're minor absences, but still an issue nonetheless.
![Apon](https://user-images.githubusercontent.com/98863380/152089307-15552b2d-d4df-47ca-80df-09215e84c607.png)

**Comment by SwiftyETH** [comment]
Unfortunately i wont be able to figure out what caused this as i wasnt provided with any possible console info, however ill keep this in mind, a part of me wonders if you placed a logic part or something that couldve caused it.
