### ISSUE TITLE
Mirror Mode Shifting

### ISSUE THREAD

**Issue by DylanG1105** [SwiftyETH/Elite-Engineering#72]
**Describe the bug**
Groups of parts when dragged a specific way can shift different parts of the group

**To Reproduce**
(I'm not entirely sure how reproduction of this works because I'm only able to do it in a specific scenario)
**Expected behavior**
Mirror mode wouldn't shift

**Screenshots**
![image](https://user-images.githubusercontent.com/81646044/152443012-7bef0774-e952-47f7-879b-9954ca47c454.png)
![image](https://user-images.githubusercontent.com/81646044/152443031-8423a41c-0e8e-47a4-9b19-9f38e2e585bc.png)
![image](https://user-images.githubusercontent.com/81646044/152443039-5632d31b-21e8-4293-b075-8ca7c19ab175.png)
it should also be noted that the same process can yield different shifts in blocks

**Desktop (please complete the following information):**
windows

**Additional context**

**Comment by SwiftyETH** [comment]
I think its fixed now?
