### ISSUE TITLE
Rotation bug after copy-pasting

### ISSUE THREAD

**Issue by Eri4474** [SwiftyETH/Elite-Engineering#73]
**Describe the bug**
When copy pasting the rotation afterwards will display the difference in angle from the opposite rotation, if you were to rotate it left  15 degrees it will display 345 Degrees.  When passing over the origin (0 degrees) it will reset and fix its self properly displaying the difference

**To Reproduce**
Copy paste a part then rotate it while watching angle

**Expected behavior**
Display the difference in angle, a 5 degree rotation should display 5 degrees not 355

**Video**

https://user-images.githubusercontent.com/98990196/152443257-20f07964-54b7-45bb-8a29-8e2999065335.mp4

**Desktop:**
Windows

**Comment by SwiftyETH** [comment]
Intentional behaviour.
