### ISSUE TITLE
Piston Issue

### ISSUE THREAD

**Issue by koloozer** [SwiftyETH/Elite-Engineering#77]
**Describe the bug**
No Boolean on pistion

**To Reproduce**
Place a piston, observe not having a red input key

**Expected behavior**
piston to move

**Screenshots**
![image](https://user-images.githubusercontent.com/98277352/152460052-fa9a55ae-67cf-485e-b628-14a73a9c3036.png)

**Desktop (please complete the following information):**
Windows 11

**Additional context**
I might stupid, but im unsure how logic works but pistons should have a red input i assume?

**Comment by SwiftyETH** [comment]
Intentional, pistons dont have an on/off state, instead you can specify the exact position you want the piston!
