### ISSUE TITLE
Logic not working with Mirror Mode

### ISSUE THREAD

**Issue by koloozer** [SwiftyETH/Elite-Engineering#84]
**Describe the bug**
Unsure if this is a bug or an intentional feature, attempting to use logic in mirrored mode does not connect to mirrored parts on the other side of the build

**To Reproduce**
Place 2 logic blocks
Attempt to connect one logic block to the other using mirrored mode
Logic blocks on other side do not connect to each other

**Expected behavior**
Logic connections should be able to be mirrored

**Screenshots**
![image](https://user-images.githubusercontent.com/98277352/152481535-526cbb21-5335-43ef-bb55-c0edf33620ad.png)

**Desktop (please complete the following information):**
 - OS: Windows 11

**Additional context**
N/A

**Comment by SwiftyETH** [comment]
Intentional. no plans of this ever having mirror mode, as the nodes itself are not mirrored!
