### ISSUE TITLE
Pistons not functioning correctly

### ISSUE THREAD

**Issue by koloozer** [SwiftyETH/Elite-Engineering#87]
**Describe the bug**
Piston not moving fown to zero when value is zero

**To Reproduce**
1. Have Speed and Acceleration set to a certain value
2. Connect to drivers seat and use
3. Observe piston not retracting

**Expected behavior**
Piston to move down when value is zero

**Screenshots**
https://streamable.com/yycblz

**Desktop (please complete the following information):**
 - OS: Windows 11

**Additional context**
N/A

**Comment by SwiftyETH** [comment]
No that makes logical sense, that piston wont move if tis acceleration and speed is zero...
