### ISSUE TITLE
noncollide broke in the new update

### ISSUE THREAD

**Issue by Loshhhs** [SwiftyETH/Elite-Engineering#9]
cannot noncollide my ball since new update

**Comment by Loshhhs** [comment]
tried to move that ball
![image](https://user-images.githubusercontent.com/81268779/150702429-4ce422c8-11c4-40c5-ba4e-fe7a77db8051.png)
![image](https://user-images.githubusercontent.com/81268779/150702433-bb6896ee-4dee-4885-a5b9-ecc62762c612.png)

**Comment by SwiftyETH** [comment]
not provided enough information, and didnt follow the guidelines. Unable to fix.
